=== TetianaShchudla/Data-Pipeline/histroy files/schema/room_def_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.datasciencetech.institute"
           xmlns="https://www.datasciencetech.institute"
           elementFormDefault="qualified">
    <!-- The root element is "culturalCenter" -->
    <xs:element name="culturalCenter">
        <xs:complexType>
            <xs:sequence>
                <!-- sub-element: "room" -->
                <xs:element name="room" type="roomInfo" maxOccurs="1000"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Define sub-elements of element "room" -->
    <xs:complexType name="roomInfo">
        <xs:sequence>
            <xs:element name="roomType">
                <xs:simpleType>
                <!-- Room type is an enumeration type -->
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Opera Theater"/>
                        <xs:enumeration value="Conference Room"/>
                        <xs:enumeration value="Dance Room"/>
                        <xs:enumeration value="Film Room"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="roomID">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <!-- roomID should have 3 digits -->
                        <xs:pattern value="[0-9][0-9][0-9]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <!-- Define number of seats in a room -->
            <xs:element name="seatNumber" type="xs:nonNegativeInteger"/>
            <!-- Define area of a room -->
            <xs:element name="area" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== TetianaShchudla/Data-Pipeline/histroy files/database/room_definition.xml
<?xml version="1.0"?>

<culturalCenter
        xmlns="https://www.datasciencetech.institute"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3.org ./room_def_schema.xsd">
    <room>
        <roomType>Opera Theater</roomType>
        <roomID>001</roomID>
        <seatNumber>200</seatNumber>
        <area>1000</area>
    </room>
    
    <room>
        <roomType>Opera Theater</roomType>
        <roomID>101</roomID>
        <seatNumber>500</seatNumber>
        <area>2500</area>
    </room>

    <room>
        <roomType>Conference Room</roomType>
        <roomID>002</roomID>
        <seatNumber>50</seatNumber>
        <area>200</area>
    </room>

    <room>
        <roomType>Dance Room</roomType>
        <roomID>003</roomID>
        <seatNumber>0</seatNumber>
        <area>200</area>
    </room>

    <room>
        <roomType>Film Room</roomType>
        <roomID>202</roomID>
        <seatNumber>150</seatNumber>
        <area>800</area>
    </room>
</culturalCenter>
